language: node_js
node_js: "10"
services:
  - mysql
branches:
  only:
  - master
  - travis
cache:
  directories:
    - node_modules
env: 
  - NODE_ENV=travis
before_install:
  - mysql -u root --password="" < db/travis.sql 
