language: node_js
node_js: 10
services:
  - mysql
branches:
  only:
  - master
cache:
  directories:
    - node_modules
env: 
  - RUN_TRAVIS_CI=0
before_install:
  - mysql -u root --password="" < db/travis.sql 
